### ISSUE TITLE
"Currently evaluating" symbol in vscode looks off

### ISSUE THREAD

**Issue by KronosTheLate** [cormullion/juliamono#104]
I guess this goes into the category of "in my opinion this glyph should be", but as it as a really really important one, I am going ahead with my comment anyways.

The problem is the little arrow bent into a circle that indicates that something is going on when evaluating code in VSCode:
![image](https://user-images.githubusercontent.com/61620837/117439970-c8ae6f80-af33-11eb-81cf-76f86b16402b.png)

IMO it looks more like a circle with a bump than the intended symbol, and could benefit from having just a teeny tiny bit of  extra visual space between the start of the circle and the arrow.

```
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)       
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =
```

**Comment by cormullion** [comment]
Yes, no problem, I've tweaked it a bit.

But I think it will always be quite small, since the U+27F3 glyph exists in JuliaMono and is the same width as all other characters. Usually, that symbol doesn't exist (of the common monospaced fonts, only JuliaMono and FiraCode have it), so the OS will substitute another glyph from a - probably not monospaced - font. On my computer, the OS uses the symbol from the STIX-General system font.

FiraCode does have this character, but it's set to be double-width.

<img width="503" alt="Screenshot 2021-05-08 at 09 42 56" src="https://user-images.githubusercontent.com/52289/117533011-2a2d1780-afe2-11eb-8be0-55ee0e9f0edc.png">

**Comment by cormullion** [comment]
Thanks! Yes - it will be in the next release and next uploaded master..
