### ISSUE TITLE
Add special thinner than monospaced `|` char for rendering purposes

### ISSUE THREAD

**Issue by IanButterworth** [cormullion/juliamono#113]
Would it be possible in the user space to add a special thinner-than-monospaced `|` char, so that segmented horizontal bars can be rendered at higher precision than monospace?

For instance, it would be nice to be able to render the information below into a more horiztonally compact space. Here the data is monospaced and wraps in the terminal
<img width="1670" alt="Screen Shot 2021-08-03 at 5 43 31 PM" src="https://user-images.githubusercontent.com/1694067/128090318-332ecfd2-797a-44e1-8f06-9836f9c62b68.png">

**Comment by cormullion** [comment]
Hi Ian. Interesting question. If you're suggesting that there could be some glyphs that don't take up the full width of a monospaced character, then I don't think this is possible. For a font to be monospaced, I think every character has to occupy the same width. Otherwise, `fontconfig` won't report the `spacing=100` and the font stops being recognised as monospace. (This happened while I was developing the font, I'd accidentally allowed some glyphs to have different widths. It was then impossible to select because fontconfig didn't allow it.)

On my terminal, having a proportionally-spaced font with thin glyphs doesn't work anyway...it looks like the width of the "m" determines the space occupied by every other glyph:

<img width="352" alt="Screenshot 2021-08-04 at 09 29 16" src="https://user-images.githubusercontent.com/52289/128148805-f2d8c5e0-e4f4-4860-afc8-63e617a008c0.png">

**Comment by IanButterworth** [comment]
Ah that makes sense. I feared this wouldn't be possible given I didn't think I'd seen it in the wild anywhere before.

Thanks for the explanation :)

**Comment by cormullion** [comment]
You could try encoding 2 bits of information as a half block character. So '01' is drawn with a right half block, 10 with a left half block, 11 with a full block, and 00 with an empty space. I think this idea is similar to the way sparse arrays are now displayed. A bit primitive though, and you can't use colour ....
