### ISSUE TITLE
The Julia banner looks strange

### ISSUE THREAD

**Issue by amrods** [cormullion/juliamono#118]
This may be just nitpicking, but with JuliaMono the banner looks weird.
<img width="568" alt="banner jm" src="https://user-images.githubusercontent.com/11388389/133708746-a34ccca7-8c98-4854-8d5e-26d936618668.png">
Can that be fixed with character or line spacing?

**Comment by cormullion** [comment]
Yes, this has been a minor source of irritation to me ever since I started designing the font.. 

A few other fonts have this problem to some extent - such as Roboto Mono:

<img width="776" alt="Screenshot 2021-09-17 at 11 14 38" src="https://user-images.githubusercontent.com/52289/133767418-8e9bb32e-05d7-489e-baf4-a2d057988922.png">

It arises if you make the parentheses and brackets larger and move the underscore character up to a better location. So there's a hard choice between code that looks right or a banner that looks right... (to my eyes, at least)

One solution is to switch on the font's OpenType stylistic set SS20, which has custom tweaked versions of various glyphs, so that the banner looks like this:

<img width="1010" alt="Screenshot 2021-09-17 at 11 34 49" src="https://user-images.githubusercontent.com/52289/133769202-431c5fc4-8146-426f-af65-6011f230c246.png">

(You might have seen this on a t-shirt... )

But I've yet to find a terminal application that supports this OpenType feature correctly. In any case, you'll have to switch it off again once the banner is no longer visible...

I  might revisit this problem one day, but I don't see any easy solution just yet.

**Comment by cormullion** [comment]
As of 0.043:

<img width="694" alt="Screenshot 2021-09-20 at 16 24 33" src="https://user-images.githubusercontent.com/52289/134028747-e8e7bff3-b786-489d-8da3-7a3a72d3a5f6.png">
