### ISSUE TITLE
Chevron/triangle characters are "too high"?

### ISSUE THREAD

**Issue by helgee** [cormullion/juliamono#13]
For example, in my tmux status line:
<img width="119" alt="grafik" src="https://user-images.githubusercontent.com/1408922/89170159-86f53080-d57f-11ea-8d7c-60c1b1eb124b.png">

v.s. Fira Code

<img width="113" alt="grafik" src="https://user-images.githubusercontent.com/1408922/89170218-9d9b8780-d57f-11ea-9aed-a8b74d432d38.png">

Great work BTW 🎉

**Comment by cormullion** [comment]
Hi Helge! Thanks for trying it out. Are these the special glyphs added to support the VIM Powerline? If so, I couldn't get these perfect  - it seems to depend on your line spacing, the terminal, the editor, the operating system, etc. For example, here the FiraCode's are too short, the JuliaMono's are too long:

<img width="690" alt="Screenshot 2020-08-03 at 10 58 05" src="https://user-images.githubusercontent.com/52289/89171034-742b2d80-d578-11ea-9e72-88e5ac2ee68c.png">

You might be able to adjust the line spacing a bit? 

I'm not sure how to change them so that they always work... :)

**Comment by helgee** [comment]
> Are these the special glyphs added to support the VIM Powerline?

Yes. For the record, this on macOS 10.15 and iTerm2 3.3. I found a workaround which is to activate the following option in the iTerm preferences:
<img width="207" alt="Bildschirmfoto 2020-08-03 um 13 44 10" src="https://user-images.githubusercontent.com/1408922/89179159-7482f300-d58f-11ea-9dc9-d474490198a5.png">

>  it seems to depend on your line spacing, the terminal, the editor, the operating system, etc.

This is why we can't have nice things 😭
