### ISSUE TITLE
A tiny problem with hinted '+' sign (plus sign) on Windows

### ISSUE THREAD

**Issue by chrisdcao** [cormullion/juliamono#132]
Hey, loving the font so far!

There's a tiny problem I notice in the '+' when being hinted by windows. If possible, can you fix it in the near future? You have my eternal gratitude man!

Here's the picture:
![Screenshot_121](https://user-images.githubusercontent.com/68319923/156982981-fcbe0665-370b-4110-86a2-61ea6a9c3c6a.png)

P/S: This hinting happens when the font is used at size 10pt, which is ~13px I guess..

**Comment by cormullion** [comment]
Hi Chris. Thanks for the report. You're right, that's Windows hinting at work, and it sometimes does a poor job... (It's a bit disheartening sometimes to see how the designs are mangled... 😦)

Because this is a big font, it's autohinted by `ttfautohint`, so I have no control over the hinting for individual characters. As a result, there's nothing I can do about this particular character: we lost the hinting lottery this time. Some fonts are manually hinted, and will work better at very small sizes on Windows - these may be a better bet for your particular use case.
