### ISSUE TITLE
Sizing of nerd glyphs looks too small

### ISSUE THREAD

**Issue by musm** [cormullion/juliamono#134]
Fira Nerd Font
<img width="293" alt="image" src="https://user-images.githubusercontent.com/4319522/158525501-050be7d4-0f83-45a4-b926-315518840730.png">
Julia Mono
<img width="291" alt="image" src="https://user-images.githubusercontent.com/4319522/158525522-775a7091-ce29-4091-b8ec-56b7ae0f97e0.png">

Basically it looks like such glyphs are slightly too small.

**Comment by cormullion** [comment]
Yes, the Fira Nerd glyphs are quite big - not sure if they're slightly too big though... 😃

But seriously, if you could post the two lines as text (rather than as image), I can see which Unicode glyphs are being used.

I suspect that nerd font icons are not indulging in ideal behaviour as befits a monospaced font. Here's the Cascadia Nerd font:

<img width="899" alt="Screenshot 2022-03-16 at 10 22 01" src="https://user-images.githubusercontent.com/52289/158569079-d2fdbf43-7414-4ffb-a546-094837426f3f.png">

And here's another nerd font (Bitstream Vera Nerd):

<img width="933" alt="Screenshot 2022-03-16 at 10 20 27" src="https://user-images.githubusercontent.com/52289/158569091-9f479c39-b482-4d40-b7f0-67208bfc4558.png">

And here's JuliaMono:

<img width="950" alt="Screenshot 2022-03-16 at 10 20 41" src="https://user-images.githubusercontent.com/52289/158569085-03c6fee0-f6bc-422b-9011-bdef2688773f.png">

Yes, the glyphs are smaller. But they don't need spaces either side...

If you really need the larger glyphs, you could try patching JuliaMono to make it a Nerd Font, but I've not done that, and wouldn't know it would work by overwriting existing glyphs anyway.

**Comment by cormullion** [comment]
>Is your point that the Nerd glyphs are not correctly spaced?

Yes.

**Comment by refaelsh** [comment]
I have the same problem.

**Comment by musm** [comment]
Interesting comment
https://github.com/ryanoasis/nerd-fonts/issues/731#issuecomment-1008293952
