### ISSUE TITLE
Mapping Roundhand style glyphs (and other alternates) into Private Use Area

### ISSUE THREAD

**Issue by DanielMGessel** [cormullion/juliamono#148]
I have been unable to get some of the tools I use (kitty & Emacs are my go-tos) to change mathematical script rendering in response to either VS1 or VS2. From what I understand about Unicode so far, Variation Selectors can be ignored by conformant implementations, so I am not sure if this would be considered a "bug" in any of the tools (or just a failure in my own configuration attempts). If it is straightforward (ideally, without duplicating the glyph definitions), mapping variants into a Private Use area would make them accessible in a wider variety of tools.

**Comment by cormullion** [comment]
I’ve read about this feature but not seen it working in the wild. Can you show it working with another font?

**Comment by DanielMGessel** [comment]
No, I don't know of another font that provides both script styles. I don't know if there is any standardized mechanism in the font formats so implementation details might be font specific. In kitty, I can switch to Roundhand with a `font_features JuliaMono-Bold +ss15` line in kitty.conf, but not "dynamically" with a variation sequence. I have opened a discussion in the kitty repo, so hopefully I'll know soon if it's supported there. Other than the emoji selectors, VS15 and VS16, which seem pretty robust across the board, I'm just sorting out what to expect.

Emacs also has a way to remap the display of individual characters which could take advantage of PUA codepoints.

I'm sure you're familiar with the [Math Calligraphic](https://www.unicode.org/L2/L2020/20275r-math-calligraphic.pdf) document. The use case is interesting; I read an implied semantic distinction between the two variations, but I'm just scratching surfaces right now.

**Comment by cormullion** [comment]
After https://github.com/cormullion/juliamono/issues/124, I added the necessary codes to the font, but it turns out that this feature wasn't implemented in the current version of the software that builds the font (the Glyphs app). So one reason it won't work at the moment is that the font doesn't support it. 😧

If the app ever gets updated to build the font with this feature enabled, I'll make another release. 

If no other font in the universe supports this feature, I don't feel so bad...😂

**Comment by DanielMGessel** [comment]
So there is a standard font encoding of the variations that can be chosen with the selectors? That’s good news! Okay - thanks for the info! Hopefully the pieces will fall into place, since you’ve done the design work for the font!

**Comment by cormullion** [comment]
I've made a bit of progress on this issue:

<img width="438" alt="Screenshot 2022-09-03 at 16 01 51" src="https://user-images.githubusercontent.com/52289/188276446-40c12ed7-2dd1-437e-aa3e-fb0fb6e522c5.png">

but there are other issues that are holding things up. :( 

Also, it turns out that support for Variation Selectors is, like some other advanced features of OpenType, not fully supported by every application (ie editors, terminals, etc.) anyway. 🤷

**Comment by DanielMGessel** [comment]
I'm designing libraries for my "Once and Future Projects" and I'm still working over internal representations. What actually works (now? later?) goes into the decision process, so I appreciate the efforts! IIUC Harfbuzz is one standard font rendering engine (the kitty Terminal Emulator and Emacs both use it). Maybe it's responsible for handling the VSs. Are you familiar with Harfbuzz?

**Comment by cormullion** [comment]
Closing, as these are now working (0.046).

**Comment by DanielMGessel** [comment]
Sorry to ping a closed issue (I'm adding this comment mainly out of due diligence), but I read in section 22.2 of the [Unicode 15.0 standard](https://www.unicode.org/versions/Unicode15.0.0/ch22.pdf) (at the top of page 856):

> Note that variation sequences are not defined for the bold script alphabet,
> nor for lowercase letters of the regular script alphabet, as there is no evidence
> of systematic distinctive use of variant styles for those ranges.

Alas, if you have created both calligraphic and roundhand in lowercase and bold, they are not simultaneously accessible within the standard so placement in the PUA might still be of interest.
