### ISSUE TITLE
Incorrect shape on BLOCK SEXTANT glyphs (added space above and below)

### ISSUE THREAD

**Issue by imneme** [cormullion/juliamono#156]
These glyphs from the _Symbols for Legacy Computing_ are supposed to subdivide the FULL BLOCK (U+2588) glyph. These are important, as they could be used for in-terminal graphics much like the QUADRANT glyphs can be. You get the QUADRANT glyphs right, but the SEXTANT ones don't have space above and below.

**Comment by cormullion** [comment]
Hi, thanks! Can you point me to an example font showing what they should look like? I was just working from the code charts which are a bit vague for space indications...

**Comment by imneme** [comment]
The [3270 font](https://github.com/rbanffy/3270font) is fairly good, but the key thing is to take your FULL BLOCK (U+2588) glyph and cut it into six pieces, via a vertical cut down the exact center, and two horizontal cuts splitting it into exact thirds.

**Comment by imneme** [comment]
(In particular, the reason there _isn't_ a “BLOCK SEXTANT-123456” glyph is because would be identical to the FULL BLOCK glyph.)

**Comment by cormullion** [comment]
Should be in the next release:

<img width="578" alt="Screenshot 2023-01-31 at 10 52 39" src="https://user-images.githubusercontent.com/52289/215740857-45b5c5a4-7214-4db9-bfb4-17474ec8d313.png">

**Comment by imneme** [comment]
Fantastic, thanks so much!

**Comment by imneme** [comment]
Hi again @cormullion — I got to try out the updated font the other day (thanks!!), and I noticed that there are a few other characters that don't fill the block the way they're supposed to:

Here's the IBM 3270 font:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/7436781/219240429-e1f37b46-780b-4cb9-9704-158c6f594434.png">

And here's Julia Mono:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/7436781/219241281-6e574c43-187f-4545-8586-c3d3ec10a6ec.png">

Specifically, U+1fb95 to U+1fbae and U+25e2…U+25e5. The second range may be more contentious, but the _Smooth mosaic terminal graphic characters_ omit these triangles specifically on the basis they already exist as “black upper left triangle” etc. If those don't match, the _Smooth mosaic terminal graphic characters_ can't really be fully used.

**Comment by imneme** [comment]
For more about this stuff, including images of how these looked, see [this document](https://www.unicode.org/wg2/docs/n5028-19025-terminals-prop.pdf).

**Comment by cormullion** [comment]
I started updating these, but the diagonal/triangular shapes are lost when the blocks are sized sufficiently vertically (to match a full block), and they don't join together unless the line spacing is exactly right (which depends on the terminal/app anyway).   

(https://github.com/cormullion/juliamono/issues/145)

So I don't think this font will be useful for actually drawing "teletext" graphics with seamlessly joining glyphs - for that, you should use a font with proper square glyphs. The glyphs as they are now can of course be used when, eg, writing about the glyphs, or coding using them... 

I think U+25E2... U+25E5 are intended to represent geometric shapes rather than be used to fill space on screen... 

It would make sense to provide all these characters in a font with a much squarer glyph design, though!
