### ISSUE TITLE
Contextual alternates for `<5->`

### ISSUE THREAD

**Issue by xukai92** [cormullion/juliamono#16]
When using Beamer in LaTeX, things like `<5->` is quite often typed.
JuliaMono would render them by combining `->`, which is what I don't want in this situation.
Is there a way to optionally disable it if there is not space between `->` (or some other criteria)?

**Comment by cormullion** [comment]
Hi. I suppose if there were some rules about which characters were disallowed in Julia before `->` I could add a kind of wildcard feature, so that `x->` prevented the combination of `-` and `>` when preceded by any `x`. We'll have to refer to the Julia parser rules for that, since Julia syntax is quite rich....

However, you should be able to disable the contextual alternates in LATEX. I have this example to enable them:

```
\newfontfamily \JuliaMono {JuliaMono-Regular.otf}[
    Path      = /Users/me/Library/Fonts/,
    Extension = .otf
    ]
\newfontface \JuliaMonoMedium{JuliaMono-Regular}
\setmonofont{JuliaMonoMedium}[
    Contextuals=Alternate                                                                      <----------------
]
```

so perhaps if you didn't include that line you could use the font without contextual alternates...?

**Comment by xukai92** [comment]
Thanks for the quick reply.
I should have said that I'm editing LaTeX files using VS Code,
so I suppose I should do the "alternate" trick but for VS Code?

**Comment by cormullion** [comment]
OK, so you'll want something from [here](http://localhost:8000/faq/#how_do_i_control_features_in_css_in_atomjuno_or_vs_code).

**Comment by xukai92** [comment]
Thanks!
