### ISSUE TITLE
Combining diacritics, eg Degree unit, U+00B0 DEGREE SIGN, with U+0323 COMBINING DOT BELOW are not rendering properly

### ISSUE THREAD

**Issue by irww** [cormullion/juliamono#170]
Degree unit, U+00B0 DEGREE SIGN, with U+0323 COMBINING DOT BELOW is not rendering properly using juliamono. 

In this example,

1°̣25

The decimal point should be directly under the degree unit.

Liberation Mono is the only monospaced font that I have found that renders this combination correctly.

**Comment by cormullion** [comment]
Version?

**Comment by anderslundstedt** [comment]
The following is probably related.

I have been meaning for a while to get back to https://github.com/cormullion/juliamono/issues/137. That issue was most likely completely fixed in v0.044 but v0.045 introduced something very similar again. Now that this issue has been brought up, I took time for a quick investigation into how v0.049 handles the whole [Combining Diacritical Marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) block.

The problem seems mainly to be with some diacritical marks that are typeset below glyphs. There are also some alignment problems (with respect to the alignment of similar marks) with some marks that are typeset above glyphs.

The following is in TextEdit on Mac OS. Problematic "below" marks are colored red, and alignment problems are colored orange. (I did not spend much time with this so I cannot guarantee that I have identified all problematic cases.)

<img width="894" alt="Screenshot 2023-05-19 at 18 49 57" src="https://github.com/cormullion/juliamono/assets/4514101/527be130-9b39-453b-9be7-cca780d08585">

There are even more problems when typesetting with XeLaTeX:

<img width="680" alt="Screenshot 2023-05-19 at 19 02 07" src="https://github.com/cormullion/juliamono/assets/4514101/2ca68a0e-5f8b-4423-babb-4352f48b7ec7">

(I currently do not have time to do a similar coloring of problematic typesetting in this case, but let me know if that would help and I will allocate some time for that soon.)

The following Python script was used to create the raw text for the table:

```
#! /usr/bin/env python3

combining_diactrical_marks_code_points = range(0x0300, 0x0370)
print(' '*6 + '│' + ' 0 1 2 3 4 5 6 7 8 9 A B C D E F')
print('─'*6 + '┼' + '─'*0x10*2, end='')
for i, code_point in enumerate(combining_diactrical_marks_code_points):
    if i % 0x10 == 0:
        print()
        print('U+0' + hex(code_point)[2:4] + 'x│', end='')
    # ignore U+034F Combining grapheme joiner
    if code_point != 0x034F:
        print(' U' + chr(code_point), end='')
print()
```

**Comment by irww** [comment]
Running Windows 11 64 bit

juliamono MediumItalic Release v0.049

![Screenshot 2023-05-19 101342](https://github.com/cormullion/juliamono/assets/75098563/c18da688-760d-43d9-b1ae-0094a160d98f)


rendered on Microsoft Word 2021

**Comment by cormullion** [comment]
@irww Since I don't have Windows or Word, could you show me how some other monospaced fonts render this combination in Word - if they're open source fonts I may be able to check how they implement this combination and fix my implementation.

@anderslundstedt Probably best as a separate issue -  if this issue is specifically about degree sign/combining dot...

**Comment by irww** [comment]
Liberation Mono is the only monospaced font that I have found that displays degree sign/combining dot correctly on Windows 11.

![Screenshot 2023-05-19 161521](https://github.com/cormullion/juliamono/assets/75098563/d70b6736-fea3-44b0-b570-94db9275d59b)

Github liberation-fonts website at
[https://github.com/liberationfonts/liberation-fonts](url)

Thanks for your attention but please don't waste your time on this.  Of the entire repertoire of stock Windows 11 fonts, only Cambria and Sitka correctly display degree sign/combining dot.

**Comment by cormullion** [comment]
@irww Thanks for the link - it appears that this topic is an active issue (https://github.com/liberationfonts/liberation-fonts/issues/45) and getting the right results will depend on both the font and the application rendering it.

I'll keep this issue open and try to address the anchor bugs some day.

**Comment by anderslundstedt** [comment]
> @anderslundstedt Probably best as a separate issue - if this issue is specifically about degree sign/combining dot...

Sure, will do some further investigations and then open an issue—probably later this week.

**Comment by cormullion** [comment]
@anderslundstedt 

I made some progress on this, so the next release, v0.050, might be a bit better.

<img width="767" alt="Screenshot 2023-05-31 at 16 47 46" src="https://github.com/cormullion/juliamono/assets/52289/166535a5-fd29-4871-bf90-dc9624a620c2">

**Comment by anderslundstedt** [comment]
Looks better now! Still some problems in XeLaTeX and LuaLaTeX … I will do some thorough investigations and then open a separate issue.
