### ISSUE TITLE
Thoughts on ligatures / stylistic set support for `!=`, `===`, and similar?

### ISSUE THREAD

**Issue by jesseleite** [cormullion/juliamono#181]
Hi there! 

Firstly, thank you so much for all your work on Julia Mono... This is a beautiful font! ❤️‍🔥

Anyway, I'm curious about ligatures / stylistic set support for `!=`, `===`, and similar?

![CleanShot 2023-07-31 at 21 09 20](https://github.com/cormullion/juliamono/assets/5187394/7c17240c-d060-4d8b-924e-caa3328c5430)

Some of those even look fine in the text area there, but are more noticeable in wezterm when the ligatures / stylistic sets render a bit thicker...

![CleanShot 2023-07-31 at 21 21 56](https://github.com/cormullion/juliamono/assets/5187394/952566af-9314-4652-838e-e9a5bf522a5b)

What are your thoughts? ❤️

**Comment by cormullion** [comment]
Hi! Thanks for the kind words!

I do have mixed thoughts about ‘ligatures’ :) -- [see this](https://juliamono.netlify.app/#contextual_and_stylistic_alternates_ligatures) -- although to be honest I don't think I have very strong reasons for either including them or not including them, other than noticing how much extra work is involved when a font designer enthusiastically adopts ligatures. Eg see FiraCode, where a lot of development effort is dedicated to them.

I think there are some interesting arguments for and against each of the character pairs/sets being replaced by a new ligature.

For example, perhaps `!=` should be replaced by Unicode `≠` rather than by a synthetic two-character version - although obviously some languages won't support that character. But the two character version is probably a more legible design than the single character, so it might be a good addition.

With the triple equals, there are two problems (in my view of course :)). One is that a better, more compact, and less clumsy replacement is the mathematical operator U+2261 `≡`, the second is that, if you're typing `===` it's important to see how many equals signs you've typed, so the gaps between them are important. So I don't think the 3-char version is much of an improvement, and the joining of the lines doesn't help.

Similarly I don't see why two plus signs (`++`) should be merged together to form some new 'gate'-like character. Or why `www` is worth turning into a saw-tooth wave character.

So my thoughts are that I think the best use for this OpenType feature is to replace an ugly combination with a better looking one. So far, that's mainly been arrows made out of angle brackets... :)
