### ISSUE TITLE
Combining characters with lower case j doesn't always render the combining character for some glyphs.

### ISSUE THREAD

**Issue by toebes** [cormullion/juliamono#199]
I really like the font!  Great job there.  However, I'm finding that some of the combining characters don't appear to work with the lower case letter j.

In this case I am using it as a webfont for the Codebusters website when generating a Baconian cipher.  However, for some of the combining glyphs, it simply doesn't render for the letter j only with the JuliaMono font.  I've pasted the list below and included a screen snapshot to show how it renders both with JuliaMono and with Courier New.  I considered that it might be related to descenders and included the letter y to show that it is specific to the letter j.  Unfortunately I can't make the bug report here use the font and github's mono font does appear to render it correctly.

```
GRAVE BELOW \u0316 - JuliaMono: J̖i̖j̖k̖y̖ Other:J̖i̖j̖k̖y̖
ACUTE BELOW \u0317 - JuliaMono: J̗i̗j̗k̗y̗ Other:J̗i̗j̗k̗y̗
CIRCUMFLEX BELOW \u032d - JuliaMono: J̭i̭j̭k̭y̭ Other:J̭i̭j̭k̭y̭
TILDE BELOW \u0330 - JuliaMono: J̰ḭj̰k̰y̰ Other:J̰ḭj̰k̰y̰
MACRON BELOW \u0331 - JuliaMono: J̱i̱j̱ḵy̱ Other:J̱i̱j̱ḵy̱
BREVE BELOW \u032e - JuliaMono: J̮i̮j̮k̮y̮ Other:J̮i̮j̮k̮y̮
INVERTED BREVE BELOW \u032f - JuliaMono: J̯i̯j̯k̯y̯ Other:J̯i̯j̯k̯y̯
DOT BELOW \u0323 - JuliaMono: J̣ịj̣ḳỵ Other:J̣ịj̣ḳỵ
DIAERESIS BELOW \u0324 - JuliaMono: J̤i̤j̤k̤y̤ Other:J̤i̤j̤k̤y̤
RING BELOW \u0325 - JuliaMono: J̥i̥j̥k̥y̥ Other:J̥i̥j̥k̥y̥
CARON BELOW \u032c - JuliaMono: J̬i̬j̬k̬y̬ Other:J̬i̬j̬k̬y̬
VERTICAL LINE BELOW \u0329 - JuliaMono: J̩i̩j̩k̩y̩ Other:J̩i̩j̩k̩y̩
DOUBLE VERTICAL LINE BELOW \u0348 - JuliaMono: J͈i͈j͈k͈y͈ Other:J͈i͈j͈k͈y͈
COMMA BELOW \u0326 - JuliaMono: J̦i̦j̦k̦y̦ Other:J̦i̦j̦k̦y̦
LEFT TACK BELOW \u0318 - JuliaMono: J̘i̘j̘k̘y̘ Other:J̘i̘j̘k̘y̘
RIGHT TACK BELOW \u0319 - JuliaMono: J̙i̙j̙k̙y̙ Other:J̙i̙j̙k̙y̙
UP TACK BELOW \u031d - JuliaMono: J̝i̝j̝k̝y̝ Other:J̝i̝j̝k̝y̝
DOWN TACK BELOW \u031e - JuliaMono: J̞i̞j̞k̞y̞ Other:J̞i̞j̞k̞y̞
MINUS SIGN BELOW \u0320 - JuliaMono: J̠i̠j̠k̠y̠ Other:J̠i̠j̠k̠y̠
LOW LINE \u0332 - JuliaMono: J̲i̲j̲k̲y̲ Other:J̲i̲j̲k̲y̲
DOUBLE LOW LINE \u0333 - JuliaMono: J̳i̳j̳k̳y̳ Other:J̳i̳j̳k̳y̳
RIGHT HALF RING BELOW \u0339 - JuliaMono: J̹i̹j̹k̹y̹ Other:J̹i̹j̹k̹y̹
EQUALS SIGN BELOW \u0347 - JuliaMono: J͇i͇j͇k͇y͇ Other:J͇i͇j͇k͇y͇
LEFT ANGLE BELOW \u0349 - JuliaMono: J͉i͉j͉k͉y͉ Other:J͉i͉j͉k͉y͉
LEFT ARROWHEAD BELOW \u0354 - JuliaMono: J͔i͔j͔k͔y͔ Other:J͔i͔j͔k͔y͔
RIGHT ARROWHEAD BELOW \u0355 - JuliaMono: J͕i͕j͕k͕y͕ Other:J͕i͕j͕k͕y͕
RIGHT ARROWHEAD AND UP \u0356 - JuliaMono: J͖i͖j͖k͖y͖ Other:J͖i͖j͖k͖y͖
ASTERISK BELOW \u0359 - JuliaMono: J͙i͙j͙k͙y͙ Other:J͙i͙j͙k͙y͙
LEFT HALF RING BELOW \u031c - JuliaMono: J̜i̜j̜k̜y̜ Other:J̜i̜j̜k̜y̜
PLUS SIGN BELOW \u031f - JuliaMono: J̟i̟j̟k̟y̟ Other:J̟i̟j̟k̟y̟
BRIDGE BELOW \u032a - JuliaMono: J̪i̪j̪k̪y̪ Other:J̪i̪j̪k̪y̪
INVERTED DOUBLE ARCH BELOW \u032b - JuliaMono: J̫i̫j̫k̫y̫ Other:J̫i̫j̫k̫y̫
INVERTED BRIDGE BELOW \u033a - JuliaMono: J̺i̺j̺k̺y̺ Other:J̺i̺j̺k̺y̺
SQUARE BELOW \u033b - JuliaMono: J̻i̻j̻k̻y̻ Other:J̻i̻j̻k̻y̻
SEAGULL BELOW \u033c - JuliaMono: J̼i̼j̼k̼y̼ Other:J̼i̼j̼k̼y̼
LEFT RIGHT ARROW BELOW \u034d - JuliaMono: J͍i͍j͍k͍y͍ Other:J͍i͍j͍k͍y͍
UPWARDS ARROW BELOW \u034e - JuliaMono: J͎i͎j͎k͎y͎ Other:J͎i͎j͎k͎y͎
DOUBLE RING BELOW \u035a - JuliaMono: J͚i͚j͚k͚y͚ Other:J͚i͚j͚k͚y͚
```

![image](https://github.com/cormullion/juliamono/assets/12609253/059d6034-9fdb-4dbf-a731-4c4ff47e0b0e)

**Comment by cormullion** [comment]
I'll look into it! What version of the font (check glyph U+E843 perhaps ) and what text environment are you working in?

**Comment by toebes** [comment]
![image](https://github.com/cormullion/juliamono/assets/12609253/fcd0f6e5-16b4-4b7f-8312-1f6d44f9a8cd)
Running in Chrome on Windows 11 (rendered from a web page). Problem also shows up in Word.

**Comment by cormullion** [comment]
This looks like one of those weird situations where it's hard to know what the problem is and thus how to fix it. I can and can't reproduce it, depending on what application I'm using (MacOS only though).

Safari browser is quite happy, as long as the CSS line height is sufficient: 

<img width="865" alt="Screenshot 2024-01-08 at 09 45 01" src="https://github.com/cormullion/juliamono/assets/52289/1086b08a-78df-4a59-866f-46195ecb760e">

But Firefox browser refuses point blank:

<img width="831" alt="Screenshot 2024-01-08 at 09 58 49" src="https://github.com/cormullion/juliamono/assets/52289/d52d6762-cda2-4c36-ad4f-d22c89f29cc1">

In a Terminal, it also looks OK:

<img width="718" alt="Screenshot 2024-01-08 at 09 46 26" src="https://github.com/cormullion/juliamono/assets/52289/3e1f4c26-42c9-4701-ba78-d07d25b98a31">

although some other terminals are unhappy (eg Kitty):

<img width="889" alt="Screenshot 2024-01-08 at 09 47 55" src="https://github.com/cormullion/juliamono/assets/52289/3fc95461-25b6-48d5-bc4f-2de8eb0d1844">

Some text editors are quite happy (eg CotEditor):

<img width="688" alt="Screenshot 2024-01-08 at 10 00 27" src="https://github.com/cormullion/juliamono/assets/52289/cec987c5-4381-42b3-a296-194563fffc8f">

Others try their best but don't really get it right (eg BBEdit):

<img width="744" alt="Screenshot 2024-01-08 at 10 01 39" src="https://github.com/cormullion/juliamono/assets/52289/37038386-78d7-4041-8167-7a0e158394b6">

I speculate that, because the "j" + "mark" is pushing the limits of the bottom of the font, some applications will just say "No", particularly if the current line height tells them to. (Some applications let lines overlap, others don't.)

Also I discovered that the "j" character is not considered by font building apps to have any mark attachments at all, so the "j"  in JuliaMono doesn't by default have a bottom mark anchor (although it's easy to add). It's therefore possible that some applications don't bother to do marks on "j" glyphs. I don't know for sure - seems odd that they would check, to be honest.

Adding a bottom anchor is easy (can be in the next release)  but might not always change the geometry problem or persuade applications to show what they don't want to. JuliaMono has long descenders, and it's not easy to change them.

So, short of increasing the available line height to give some encouragement to applications that need it, I can't see a quick solution.

**Comment by toebes** [comment]
I've done some more playing and interestingly enough, on the Mac with Chrome the j renders correctly.  I've tried tweaking line height on Windows, but it doesn't seem to have an impact.  However, I did observe something.  It isn't that the annotation isn't there, but the annotation is shifted off to the right.   Here's an example that it is obvious with:

M̳j̳y̳y̳j̳   
![image](https://github.com/cormullion/juliamono/assets/12609253/4fbba0ed-a08c-436f-a883-52c78dcb15c0)


And another:  M̲jy̲yj̲

![image](https://github.com/cormullion/juliamono/assets/12609253/7cfb39d5-a206-43c8-872a-0add5ff9c014)

**Comment by cormullion** [comment]
It's all quite frustrating for font makers and font users... I hope you can find a solution - perhaps another font - that works more reliably for you!

**Comment by toebes** [comment]
But your font is excellent!  
For now, my code just makes sure not to pick those specific descenders when using the letter j.  I'm happy to try anything else if you get any insights!
