### ISSUE TITLE
Request for 450 font weight

### ISSUE THREAD

**Issue by chmielcode** [cormullion/juliamono#200]
Would it be possible to add a new weight between Regular [400] and Medium [500]? I'm using JuliaMono with Medium as Regular (renamed with FontForge), but it looks to bold. I'm on Windows 11 with 150% scaling on a WQHD display and only "a little bit thicker" fonts like JetBrains Mono, Maple Mono, Hermit or DejaVu Sans Mono render 100% clear and readable in all apps. JuliaMono has some great features, but it's sometimes hard to read on my setup. I propose weight 450 called Retina (like Fira Code).

**Comment by cormullion** [comment]
Hi. I made a quick 450 weight version here: 

[JuliaMono-Book.ttf.zip](https://github.com/cormullion/juliamono/files/14258346/JuliaMono-Book.ttf.zip)

I've used a more widely-adopted standard name - "Book" - rather than the FiraCode term "Retina" (which is an Apple registered trademark apparently).

If this works for your use case, I'll set about adding it to the set of exported weights when I make a new release...

(I don't use Windows and so I don't know how well fonts that are autohinted (rather than manually hinted) look.)

**Comment by chmielcode** [comment]
Thank you for this sample :) It looks better, but still not as clear as medium weight (some lines are to thin and look blurry). On the up side the difference between Book and Bold is much easier to spot. Maybe 475 would do the trick? I don't know and don't really want to bother you. Keep up the good work 👍 Thanks
