### ISSUE TITLE
Emoji Presentation for Julia Logo

### ISSUE THREAD

**Issue by mnemnion** [cormullion/juliamono#201]
> add more glyphs? Well, perhaps if lots more people ask...

This is an "add more glyphs" feature request, yes. 

In a [thread on the Discourse](https://discourse.julialang.org/t/what-is-the-most-julia-associated-emoji-character/111337/6) the question was raised of which emoji is the most Julia-associated. I pointed out that your excellent font has the logo in the Private Use Area, albeit in monochrome, as is normal for anything but emoji. 

What would be rather nice would be to add a full-color double-width emoji variation of the logo.  This shouldn't be a new codepoint, but rather, a ligature of the existing logo with the [emoji presentation selector](https://www.unicode.org/reports/tr51/#def_emoji_presentation_selector).  *Typing* this could be a bit of a challenge, but you could add `print("\ue800\ufe0f")` to the documentation, which would print it at the REPL, where it could then be copy-pasted at leisure. 

Something to consider, I hope. I know that I'd use it.

**Comment by cormullion** [comment]
> > add more glyphs? Well, perhaps if lots more people ask...
> 
> This is an "add more glyphs" feature request, yes.

I must edit that to read "monochrome" 😂

I'll investigate this. Last time I looked, colored glyph support was a bit of a mess, with multiple competing formats and spotty support from browsers and applications. But it's been a few years, so perhaps the formats and support situation has improved since then.

**Comment by mnemnion** [comment]
Colored fonts are reasonably well supported at this point in time, thanks to emoji.  One of the nice things about the emoji presentation selector is that renderers which don't support it will fall back to the monochrome glyph. 

I know little about fontography, but three colored dots without any detail or gradients is about the least demanding emoji possible. And I know that OpenType supports SVG fonts, so "define ligature on variation selector, drop SVG of Julia logo in the font" might be all it takes if SVG in fonts is sufficiently well-supported. If not, bitmaps would work well for three circles, and support for the oldest color font formats is practically speaking ubiquitous now. 

Whatever you decide is of course fine. I'll also just add that "the Julia font has one color glyph, the Julia logo, and will not be adding more" is a defensible position to take. In case you're concerned about letting the camel's nose into the tent.

**Comment by cormullion** [comment]
It's easy enough to add, fortunately. Initial results are mixed. I think the idea is that the colored version is shown automatically if present (no selector required).

Success in Terminal and iTerm (MacOS):

Terminal:

<img width="399" alt="Screenshot 2024-03-10 at 10 17 13" src="https://github.com/cormullion/juliamono/assets/52289/ff829ab0-1211-45bc-a461-0f7e685aecef">

iTerm:

<img width="405" alt="Screenshot 2024-03-10 at 10 20 20" src="https://github.com/cormullion/juliamono/assets/52289/60706a5f-352e-453c-9184-b0c71b439467">

iTerm:

<img width="436" alt="Screenshot 2024-03-10 at 10 31 48" src="https://github.com/cormullion/juliamono/assets/52289/18021b0f-5396-479e-a90e-75c3cb78939e">

WezTerm: No response in WezTerm, which is concerning, since the font support is usually great:

<img width="401" alt="Screenshot 2024-03-10 at 10 28 49" src="https://github.com/cormullion/juliamono/assets/52289/25190bda-113f-45b2-b543-921fd49862a7">

Well-behaved Mac apps are happy to automatically show a colored version:

Cot Editor (left) and Pages:

<img width="1203" alt="Screenshot 2024-03-10 at 10 29 57" src="https://github.com/cormullion/juliamono/assets/52289/9d2b4034-7a6c-4616-b139-539a6e8d2fcd">

But VS-Code unfortunately doesn't do a good job:

<img width="748" alt="Screenshot 2024-03-10 at 10 18 48" src="https://github.com/cormullion/juliamono/assets/52289/9644717d-6362-43dd-adcb-86031d78e7e2">

seeming to default to black if a colored glyph is detected in the font...?

If you want to have a go yourself, here are three TTF fonts with the colored version of E800 added:

[Archive.zip](https://github.com/cormullion/juliamono/files/14549815/Archive.zip)

**Comment by mnemnion** [comment]
> It's easy enough to add, fortunately. Initial results are mixed. I think the idea is that the colored version is shown automatically if present (no selector required).

I installed the patched fonts, the idea here is that `'\ue800'` becomes the colorful version of the font? Valid choice, the suggestion of a ligature with the emoji presentation selector was that the base glyph could stay as-is, and with the selector would be in color (and ideally double-width like an emoji). Not attached to that idea, just explaining what I meant by it. 

Can confirm: shows up in iTerm, still black and white in WezTerm, displays fine in random Mac-native programs like TextEdit. In Sublime Text... at the moment Sublime Text hard-crashes when I try to open settings or the font selector, that's what I get for running the dev build.

VSCode renders it just fine, in color, in both the editor and the terminal. I use a dark mode for both, and the text is still white on dark, the icon shows up in color in both places. VSCode 1.87.0 on macOS.

WezTerm (my daily driver) uses HarfBuzz, the rendering is more likely to be an issue with how WezTerm configures it than an inability of HarfBuzz to render, support looks [fairly complete](https://harfbuzz.github.io/harfbuzz-hb-ot-color.html#). 

I didn't go maximalist on trying it out, but wasn't able to find a program where it wouldn't render at all.  Emoji-sized would be nice to have, simply so it renders the same size as other emoji, I have a tendency to use them in terminal programs for icons. But yeah looks good ^_^.

**Comment by cormullion** [comment]
Thanks for doing some testing - I was mistaken about VSCode, I think, because after some updates and restarts it works fine in the xterm.jl terminal.

I didn't get into the emoji presentation selector business; I'm not sure quite how it works, whether it's possible to define "one's own emojis" (I see references to emoji "lists") and how to use/define selectors in a font. Perhaps I'll be able to find some more information about how other fonts implement it, but emoji handling is a deep rabbit-hole and much of the discussion is way over my head... Perhaps one day.

Although applications and terminal emulators often handle and combine emojis and different width characters from various fonts well (mostly), I think it's standard practice to ensure that every glyph in a monospaced font is the same width; I've seen reports of some fonts that don't pass some checks and therefore fail to be treated as monospace. This is another font-related rabbit-hole - which I won't be able to investigate at present ... :)

**Comment by mnemnion** [comment]
That's something I wouldn't have known about monospaced fonts. Naively, I assumed that a monospaced meant that you can have single width and double width characters, but the double width have to be precisely double the single width, and the single width all have to be one size. 

Regardless, it's your project, and I wouldn't want you to think I have any expectations of you here. I think the colored dot Julia logo looks great, I hope you consider adding it to a release at some point. Have a great week ^_^

**Comment by Dolfost** [comment]
Hello everyone. Also there is a problem with some [terminal emulators (alacritty especially)](https://github.com/alacritty/alacritty/issues/8007). It wont work with color glyphs. 

I know, this could be the alacritty's problem, but I want You all to be afraid of this.

**Comment by cormullion** [comment]
Yes I think the introduction of a single color glyph has exposed some interesting incompatibilities and undefined behaviours in a few terminal environments. Both Wezterm and Alacritty are struggling - although most of the other terminals and editors are coping OK (although I can’t test most of them).

For now I suggest you stay on version 0.054 or so. 

Given that this has caused more problems than it’s really worth, I think I’ll revert this feature in the next release.

**Comment by cormullion** [comment]
This change was introduced in v0.055, but reverted in v0.056. It seems to have uncovered some interesting problem areas in some editors and applications.
