### ISSUE TITLE
Tips for improving load speed?

### ISSUE THREAD

**Issue by fonsp** [cormullion/juliamono#24]
This is so cool! And perfect for Pluto :)

The file size is too high (1200kB for two font weights vs the current 20 kB for Roboto Mono latin+greek), but the high number of glyphs is too cool to consider changing it.

But I thought of a way to make it work: Pluto could initially load with a version of JuliaMono that only includes latin (with browser default `monospace` for other glyphs), and then swap over to full JuliaMono once it is loaded. Do you think that this is a good idea?

I noticed that the latin subset of JuliaMono is similar to Roboto Mono, but there are differences. Would it be possible to extract the latin subset from JuliaMono?

**Comment by cormullion** [comment]
Yes the size is very large now that I switched to TrueType... They're nearly twice as large as the OTF/PostScript versions. :(

Are you thinking to use the Unicode range option for `@font-face` + WOFF2 fonts that restricts the download to a subset of glyphs, then switch to a complete subset later? Might be possible for CSS wizards...

I'm wondering if you access fonts installed inside the package - kind of like how applications use their own fonts because they were installed as part of the application bundle?

Alternatively or aditionally you could make it easy for people to select the font in Pluto (they could install it themselves for general use in the REPL and then choose it for Pluto).

I *think* it would be straightforward to make a latin (MacRoman/Windows1252) version. Copy and paste is easy enough, there might be ways I could automate it too). Will investigate.

**Comment by fonsp** [comment]
About hot-swapping: I thought that we can just load two fonts: "JuliaMono" and "JuliaMono-latin". The second one will load sooner because it is smaller, and then in the CSS:
```css
code {
    font-family: "JuliaMono", "JuliaMono-latin", monospace;
}
```
When you open Pluto for the second time it will load near instantaneously - it uses a service worker to cache all assets inside the browser. 

I don't want to make it an option - I want everyone to use JuliaMono instead of Roboto Mono :)

**Comment by cormullion** [comment]
>I want everyone to use JuliaMono instead of Roboto Mono :)

Awesome - if a bit scary... :)

I'll investigate how to do it.

**Comment by fonsp** [comment]
Just being able to extract a latin subset would already be a huge help! I think the hot-swapping & CSS font loading is something that I need to learn about anyways, because Pluto also uses some other fonts that also need better loading strategies. So don't spend too much time on it!

**Comment by cormullion** [comment]
I made a smaller version called JuliaMono-RegularLatin which has the bare minimum of glyphs and is much smaller. You could compare this versus doing the unicode range subsetting in CSS.

<img width="421" alt="Screenshot 2020-08-15 at 11 30 17" src="https://user-images.githubusercontent.com/52289/90310911-e04d5000-deed-11ea-9c1b-69c20c4e31dc.png">

I can easily include add any glyphs that you must have to `-RegularLatin`...

**Comment by fonsp** [comment]
Thank so much!!!

**Comment by fonsp** [comment]
Can you also make a Latin subset of the Bold variant? ☺

**Comment by cormullion** [comment]
[Yes](https://github.com/cormullion/juliamono/releases/tag/v0.015). :)

**Comment by fonsp** [comment]
Pluto `0.12.0` will use JuliaMono! I'm using it already and it looks delightful

**Comment by cormullion** [comment]
@fonsp Thanks so much - I'm very happy about this... :)
