### ISSUE TITLE
Swap \phi and \varphi ?

### ISSUE THREAD

**Issue by martincornejo** [cormullion/juliamono#29]
Maybe it's a taste thing, but I personally prefer φ for phi (as does the standard VS Code font, not sure what it is) since it is easier to distinguish with Φ Phi (and also I find it kind of prettier than ϕ)

Currently in JuliaMono: 
|Tab completion | Character |
|----:|----:|
| \phi | ϕ |
| \varphi | φ |
| \Phi | Φ |

Could it be possible? 😅: 
|ab completion | Character |
|----:|----:|
| \phi | φ |
| \varphi | ϕ |
| \Phi | Φ |

**Comment by simeonschaub** [comment]
I think the VS code font is the inconsistent one here, since the Unicode spec is quite clear about these characters.

[U+03D5](http://www.fileformat.info/info/unicode/char/03d5/index.htm) (\phi) is described as:

> used as a technical symbol, with a stroked glyph
maps to "phi1" symbol entities

[U+03C6](http://www.fileformat.info/info/unicode/char/03c6/index.htm) (\varphi):

> the ordinary Greek letter, showing considerable glyph variation
in mathematical contexts, the loopy glyph is preferred, to contrast with U+03D5

**Comment by martincornejo** [comment]
Guess I'll close the issue then.

**Comment by Datseris** [comment]
I agree with the motivation of the original post, it is much more easy to distinguish the versions if the wigly case is used. And in fact in Greek type the wigly version is the "standard". Unfortunately, LaTeX notation does correspond `\phi` to the non-wigly version, so I am not sure whether it is advisable to go forth with this choice...

(by the way, same thing happens with the epsilons: ε is the normal Greek version that you see in school and type in real life. This corresponds to LaTeX's `\varepsilon`, while the `\epsilon` is the utterly disgusting 

![image](https://user-images.githubusercontent.com/19669089/92410012-fb089280-f142-11ea-9dab-8b365f8b6c10.png)
