### ISSUE TITLE
OTF rendering broken on Windows

### ISSUE THREAD

**Issue by pfitzseb** [cormullion/juliamono#3]
in certain sizes. I'm not sure whether it's an issue with VSCode/Atom, but these don't look right:

`pr`, `10`:
![grafik](https://user-images.githubusercontent.com/6735977/88828105-06bf7b80-d1cb-11ea-812b-8a46d9c9ed92.png)

`a`:
![grafik](https://user-images.githubusercontent.com/6735977/88828162-18a11e80-d1cb-11ea-8c9c-f69189e44c56.png)

The font looks great on the website (and/or on Linux) though, so I suspect there's a problem with the `otf`s on Windows.

**Comment by cormullion** [comment]
Probably [this](https://blog.codinghorror.com/font-rendering-respecting-the-pixel-grid/).

[I kind of half expected it to look worse on Windows](https://juliamono.netlify.app/faq/#does_it_work_on_windows)... :) 

Looks like this for me: 

<img width="1455" alt="Screenshot 2020-07-29 at 17 59 49" src="https://user-images.githubusercontent.com/52289/88830027-4daa7280-d1c5-11ea-9b9d-ff2668ee7568.png"> (14 point, enlarged, macOS)

One day I'll buy a Windows computer and make the font work better... ¯\\\_(ツ)_/¯

**Comment by simeonschaub** [comment]
Just as another data point, I observe the same rendering issues with 10pt in the Kitty terminal on Linux (Probably because of [this](https://github.com/kovidgoyal/kitty/issues/214)):

![Screenshot from 2020-07-30 20-58-46](https://user-images.githubusercontent.com/5220528/88963404-1496fe80-d2a8-11ea-9638-206187691bf0.png)

FiraCode seems to look significantly more consistent in this setting.
