### ISSUE TITLE
Beautiful typeface, but f and r glyphs don't quite harmonize with the rest

### ISSUE THREAD

**Issue by nicknack23** [cormullion/juliamono#36]
First of all: thanks so much for this contribution! I think your typeface is fantastic, clean and readable but still with character - near perfect actually. But to my eyes there are two minor inconsistencies among the standard latin letters that stick out a tiny bit.

1. Lower case f: the filial of the ascender is quite flat where I would expect it to be more curved. Compare with the upper filial of the a, s, c and r which all curve downwards a bit, or the foot of the t or l which curve similarly upwards. Would it be possible to just mirror the bottom of the t and call it a day?

2. Lower case r: this one is tricky. I think I see what you were going for by combining the slight leftward angular serif of the stem (similar to the i, j, l) with more of a curve to the right (see point 1 above). But the end result looks a bit out of place, as if a cursive glyph was dropped in among the rest. See how the three r's stick out in "Argumenterror" your screenshot below. On the other hand, your r also contributes to the typeface character so I'm a bit on the fence about it. Maybe just tone down the "cursiveness" a tiny bit?
https://juliamono.netlify.app/assets/emacs-example.png

This is all highly opinionated of course. But If you see my point here but still want to keep your original designs, would you consider providing alternate glyphs for the f and r?

**Comment by cormullion** [comment]
Hi there! Thank you for your interest and comments, they're much appreciated! 

I can easily add alternate glyphs - I don't think there's any restriction on the number of stylistic sets we can have...

One of the things I had in mind was to make sure that all the letters were easily distinguishable, since it's aimed entirely for coding, and not everyone has 5K retina iMacs... :) Perhaps this goes against an important principle of type design (about which I know very little but find fascinating :)) that the letters should all harmonize with each other, offer consistent shapes, etc. So in a way the "r" actually works better if it is out of place - no chance of being confused with other letters on low-resolution Windows monitors...   Anyway, I can see your point of view, and it probably makes good sense.

I'll explore your suggestion of a different "f" - there's a good basis for a re-design:

<img width="1212" alt="Screenshot 2020-09-09 at 12 14 44" src="https://user-images.githubusercontent.com/52289/92591774-6ca52580-f296-11ea-8c1d-4f13d7c81469.png">

**Comment by cormullion** [comment]
I added `ss09 - alternate f` in v0.015: (top: inactive, bottom: active)

<img width="491" alt="Screenshot 2020-09-15 at 17 56 49" src="https://user-images.githubusercontent.com/52289/93241134-d9c82780-f77c-11ea-9332-9386ff50d209.png">

I'm not 100% sure, but it's early days... :)

**Comment by nicknack23** [comment]
The alternate f is perfect, thanks! If you find the time for another alternate please tweak the design of the r as well, e.g. by making the stem completely straight. When the r is seen out of an English context (e.g. `r = ...`) its cursive style almost makes it look like a lower case gamma.

**Comment by cormullion** [comment]
now in `ss10`

**Comment by waldyrious** [comment]
> now in `ss10`

For reference, that was included in [v0.021](https://github.com/cormullion/juliamono/releases/tag/v0.021).
