### ISSUE TITLE
hypen sit too low

### ISSUE THREAD

**Issue by musm** [cormullion/juliamono#39]
Roboto
When raising an issue, check that you're using the latest version, and if appropriate could you add information about your operating system, hardware in use (mainly the [ppi of your monitor](https://dpi.lv) , software/editor, pixel size, etc. Thanks!
![image](https://user-images.githubusercontent.com/4319522/93366601-64f6fb00-f819-11ea-836c-d784edcd0ed1.png)

Julia Mono
![image](https://user-images.githubusercontent.com/4319522/93366625-6e806300-f819-11ea-9a05-e0fa9e2b50dc.png)

I also compared some other fonts. Visually the hypen seem to me to sit too 'low' and should be bumped up slightly higher. This is especially evident in the `3--32` text.

**Comment by cormullion** [comment]
Yes, interesting. I positioned the maths operators to align with the _lowercase_ midpoint, eg algebraic-type use (since I mostly type in lowercase).

<img width="776" alt="Screenshot 2020-09-16 at 17 43 46" src="https://user-images.githubusercontent.com/52289/93367365-5114be80-f844-11ea-8a67-c836043039b6.png">

If you use numeric literals a lot (and don't have spaces around operators) you might find the operators look like they sit a bit lower than the midpoint of the numerals/capitals.

**Comment by musm** [comment]
That makes sense, I guess this will always be an issue because people use `-` as an operator and as a dash which have different meanings.
