### ISSUE TITLE
Pipeline operator has excess vertical padding

### ISSUE THREAD

**Issue by aminya** [cormullion/juliamono#42]
![image](https://user-images.githubusercontent.com/16418197/93971666-50919180-fd36-11ea-914a-29da72338ab8.png)

Pipeline operator has excess vertical padding

**Comment by cormullion** [comment]
more info needef

**Comment by aminya** [comment]
The operator is not between the lines. Same thing with Cascadia Code PL:
![image](https://user-images.githubusercontent.com/16418197/93971607-2c35b500-fd36-11ea-9956-80e41051862a.png)

**Comment by cormullion** [comment]
Ah, that looks like the Powerline symbol 0xE0A0. It displays normally when typed in a MacOS Terminal window:

<img width="619" alt="Screenshot 2020-09-23 at 08 28 47" src="https://user-images.githubusercontent.com/52289/93980706-e5b47a80-fd76-11ea-837d-3854b72e23cf.png">

So I'm trying to reproduce your problem here: but how do you get this symbol to appear in the powerline?

Also, please specify the details of your setup (as per the Issue template :)).

**Comment by aminya** [comment]
I am on Windows 10. I use PowerShell and [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh?WT.mc_id=-blog-scottha)

You can reproduce it on Mac by installing PowerShell and oh-my-posh. Then select JuliaMono as the font.

**Comment by cormullion** [comment]
Well that took a it of installing ;)

But it works OK for me. The problem probably lies somewhere other than the font, and I may not be able to fix it.

<img width="819" alt="Screenshot 2020-09-23 at 09 36 45" src="https://user-images.githubusercontent.com/52289/93988197-57dd8d00-fd80-11ea-93cd-3f98feb350aa.png">

**Comment by aminya** [comment]
Thank you! That's weird.

I did more testing, and the simple ligatures (like `>=` are not available). Does JuliaMono require special installation? I just installed JuliaMono regular.

**Comment by cormullion** [comment]
Well `>=` isn't a ligature (in this font) (since ligatures are used carefully and infrequently, because Julia has Unicode). Try `->` or `=>` - if they don't work, then you need to enable them somehow in Powershell. 

You can often get useful font-related information from the FiraCode repo (https://github.com/tonsky/FiraCode#terminal-compatibility-list) - since he's been developing that for over six years...

**Comment by aminya** [comment]
The behavior seems strange. It works if I put echo before it:
![image](https://user-images.githubusercontent.com/16418197/93992165-d6233a80-fd52-11ea-9248-d8277e87f3e2.png)


or it works inside Julia REPL:
![image](https://user-images.githubusercontent.com/16418197/93992256-f2bf7280-fd52-11ea-9705-45e8cd4b075b.png)

I thought this font is a general-purpose font. It is fine if it is specific to Julia.

**Comment by cormullion** [comment]
Again, this looks to work OK in Powershell on MacOS.

<img width="366" alt="Screenshot 2020-09-23 at 10 16 16" src="https://user-images.githubusercontent.com/52289/93992752-d7218f80-fd85-11ea-915e-e362e95e44c8.png">

JuliaMono is a fairly general-purpose font, but it avoids the excessive ligature-use that's common in some other fonts (which are often designed for Haskell or JavaScript for example). If you like a lot of ligatures in your code, I'd recommend using FiraCode or similar.
