### ISSUE TITLE
Tab spacing in BBEdit (and other apps)

### ISSUE THREAD

**Issue by mtconleyuk** [cormullion/juliamono#53]
I'm noticing that tabs are not aligning correctly in all apps. In particular, BBEdit (which is normally highly reliable when it comes to text display) is displaying different spacing for Julia than for other mono-spaced fonts such as Menlo, Hack, Monaco, Courier, etc. XCode seems to display correctly, but other apps such as Coda, Atom, and Sublime have problems as well, indicating that perhaps there is something about the font table that's not right (and which XCode is working around somehow).

I've attached a sample file which demonstrates the problem pretty clearly, as well as a screenshot that compares the layout for Julia in both BBEdit and XCode, and another that shows the result for Hack. Text file is UTF-8, tabs are 4 spaces.

[tabbed text.txt](https://github.com/cormullion/juliamono/files/5356991/tabbed.text.txt)
<img width="1879" alt="Hack11Regular" src="https://user-images.githubusercontent.com/1219970/95621582-eff59a80-0a3f-11eb-8731-4645fbf8e881.png">
<img width="1796" alt="Julia11Light" src="https://user-images.githubusercontent.com/1219970/95621588-f126c780-0a3f-11eb-9400-057cb97947a9.png">

Julia 0.018
BBEdit version 13.5 (415039, 64-bit Intel, sandboxed)
macOS 10.15.7 (19H2)
AMD Radeon Pro 5700
5120x2880 (looks like 2560 x 1440)
30-Bit Colour (ARGB2101010

**Comment by cormullion** [comment]
Yes, I was a BBEdit user back in the day and it was always a solid application... But I felt they started dropping the ball a bit - particularly when they dropped support for OpenType features such as alternates and ligatures in BBEdit 13 (Rich told me that Apple removed a library they needed, but I felt that since other text editors were able to support them, why couldn't BBEdit....?)

If you display a text file in lots of apps, I wouldn't be _that_ surprised if the only one with glitches is BBEdit. Although to be honest there's so much variability I wonder why pro font designers don't all die young...

So here are a few editors (from the top: BBEdit, SublimeText, Xcode, VSCode, and Atom) showing your file (and showing how every application draws text slightly differently):

<img width="2854" alt="Screenshot 2020-10-10 at 08 58 37" src="https://user-images.githubusercontent.com/52289/95649791-4235ca80-0ad7-11eb-9d9a-fc88e6554875.png">

Thanks for the well-prepared issue! But I don't think there's anything to do here.

**Comment by mtconleyuk** [comment]
Thanks for the feedback. There are few bigger fans of BBEdit and Bare Bones than I, but I suppose it's possible they've overlooked something. They do tend to be pretty responsive; any chance you could contact them and see if they have a hint about this (I did file a bug report with them first, (Case 409145) Julia and Tab Spacing)? Or if I sent them a link to this issue and see if they have a suggestion?

**Comment by siegel** [comment]
Tab spacing in BBEdit is based on a calculation of the width of a nonbreaking space. Other fonts have had issues with tab spacing as well, which their designers were happy to address.

If my recollection is correct, some fonts have problems with the width specification of the NBSP glyph. (A common error is failing to ensure that NBSP is the same width as every other character in a monospaced font.) Therefore you may find it useful to look for a similar issue. (Alas, since I am not a font implementor, I regret that I am unable to speculate as to the precise nature and resolution.)

While you're at it you may find it useful to verify the correct implementation and specification of other glyphs that BBEdit uses (these are for Show Invisibles, and are not often found in user-entered text):

```
U+00B7,		//	dot
U+2022,		//	bullet
U+2206,		//	delta
U+00AC,	//	not sign
U+00B6,		//	paragraph
U+007C,		//	vertical bar
U+00BF,		//	inverted question mark
```

**Comment by cormullion** [comment]
@siegel I'm so happy to see you reply here, and thanks for the suggestions, I'll try to investigate some time. (I still use BBEdit, of course, but it's not always the frontmost application, sorry, but....😂). I'd be delighted if it was my fault, cos I could fix it.

(But .... ligatures someday?!)

**Comment by cormullion** [comment]
I made a quick check of spaces - things look OK to me.

This screen capture reproduces the original problem in BBEdit:

<img width="2352" alt="Screenshot 2020-10-20 at 13 28 11" src="https://user-images.githubusercontent.com/52289/96586184-8c3d5e00-12d8-11eb-995e-68b801800dce.png">

It's using Apple's SF Mono font at 13point , though....

**Comment by mtconleyuk** [comment]
I had a back and forth with Rich Siegel and sent him some videos demonstrating the problem in better detail. Here's what he says:-

> Here's a quick table (the values are as reported by the debugger at the point where BBEdit is capturing the font metrics):
> 
> ```
> name-size           advancement         nbsp-width
> Hack-13             7.82666015625       7.82666015625
> Inconsolata-13      6.5                 6.5
> JuliaMono-13        7.7999999999999998  7.8000000000000007
> JuliaMono-11(*)     6.5999999999999996  6.5999999999999996
> Inconsolata-11      5.5                 5.5
> Hack-11             6.62255859375       6.62255859375
> 
> ```
> The (*) next to JuliaMono-11 indicates the presence of the display anomaly.
> 
> I *think* what you're seeing is the result of accumulated rounding errors involving fractional character widths.
> 
> It's dependent not only on rendering (ATSUI still uses Fixed values for calculation, which certainly does not help) but also on the font.
> 
> I don't know how any of that stuff is supposed to work, but since there is existence proof of multiple fonts that don't have the issue, the JuliaMono author can probably look at those fonts and see if he's able to identify what they do that he doesn't (or vice versa) and make appropriate adjustments.

Here are links to a couple of QuickTime movies that demonstrate the problems I'm seeing, using different fonts within BBEdit. I think it's pretty clear that something is off within JuliaMono.
 [FontTest.mov.zip](https://www.wasmac.com/Movies/FontTest.mov.zip)
  [FontTest2.mov.zip](https://www.wasmac.com/Movies/FontTest2.mov.zip)

**Comment by cormullion** [comment]
Thanks! You've worked so hard on this issue, I wish I had some good news. Unfortunately there are hardly any "knobs" or "switches" I can flip to change horizontal spacing. Basically, every character has a width, and working on the nonbreaking space looks like this:

<img width="421" alt="Screenshot 2020-10-21 at 10 10 24" src="https://user-images.githubusercontent.com/52289/96699057-c0bb2380-1385-11eb-81c3-27bd5f0fd6a1.png">

😃 I'd love to be able to change something, anything, but there's nothing to change.

In the spirit of Rich's "there is existence proof of multiple fonts that don't have the issue", here's a selection of other fonts that show the same problem _in BBEdit_ - FIraCode, IBMPlex Mono, JetBrains Mono, Operator Mono, and Source Code Pro.

![fontissues](https://user-images.githubusercontent.com/52289/96699261-fa8c2a00-1385-11eb-86c2-3bc91ef1be02.gif)

So reluctantly I'd not recommend JuliaMono for use with BBEdit: "Only use BBEdit with Fonts that Don't Suck"!

I'll add a note to the documentation that it's not compatible with BBEdit.

**Comment by mtconleyuk** [comment]
Okay, well, thanks for the info. Too bad it hasn't worked out. Sure would be interesting to know what the problem actually is, but, there you go.
