### ISSUE TITLE
Glyph for Pluto not rendered

### ISSUE THREAD

**Issue by dav2017** [cormullion/juliamono#86]
First of all thanks for this great font.

This is a minor issue, but may a quick fix (juliamono 0.28 and previous).
When I run or compile Pluto I get something like this in the REPL:
`Welcome to Pluto v0.12.17 🎈`
but the 🎈 glyph is not rendered (instead, a rectangle with a code inside).
Thanks

**Comment by cormullion** [comment]
Hi there! 

Do you have a picture? This is what I see on macOS 

<img width="782" alt="Screenshot 2020-12-15 at 11 58 13" src="https://user-images.githubusercontent.com/52289/102212300-e3bd0c00-3ecc-11eb-94c3-109a336365a0.png">

Typically, emojis are handed over to another font for rendering, ie the "font fallback" mechanism. This might vary from OS to OS and from terminal to terminal, I suppose...

What happens if you run this Julia code:

```
for c in 0x1F300:0x1F600
     print(Char©)
end
```

**Comment by dav2017** [comment]
Hi,
I am on Linux. I didn't know of the "font fallback". I that is the case, I have to investigate.

Here the image showing what I get for Pluto:
![image](https://user-images.githubusercontent.com/33750504/102230935-b92f7b00-3eed-11eb-9dc9-5249e4793e84.png)

And here the output of the command you suggested:
![image](https://user-images.githubusercontent.com/33750504/102231074-dd8b5780-3eed-11eb-9084-c19c2410ea4f.png)

**Comment by dav2017** [comment]
Following you hint, I installed emoji fonts. Now the glyph is rendered correctly.
Thanks

**Comment by cormullion** [comment]
Glad you sorted it. Your terminal was originally showing an interesting subset of the Unicode character set. I see:

<img width="1333" alt="Screenshot 2020-12-15 at 16 29 40" src="https://user-images.githubusercontent.com/52289/102243226-d155c900-3ef2-11eb-88ea-ab2b35fbe5ee.png">

**Comment by dav2017** [comment]
Hi, thanks for caring.
Now this is my current set:
![image](https://user-images.githubusercontent.com/33750504/102266230-733bdc80-3f18-11eb-8acd-b74731addeb3.png)
