### ISSUE TITLE
Any plans on making the sources of the font available and also the build method?

### ISSUE THREAD

**Issue by cata0309** [cormullion/juliamono#90]
Hello!
Thank you for making this font! Is unexpectedly pleasant to write code with it. Any plans on releasing the sources of it to the public so others could contribute to it or at least, learn from it?
Thank you

**Comment by cormullion** [comment]
Hi! Glad to hear... This is on the list of things to look into this year, if I get round to it.  What formats do you think it should be provided in?

**Comment by cata0309** [comment]
Anything you used will be a good starting point for others. I don't quite know what would be the standard formats out there. You could have a look at https://github.com/JetBrains/JetBrainsMono

**Comment by cata0309** [comment]
@cormullion Friendly ping. Do you need any help on this?

**Comment by cormullion** [comment]
Hi! Indeed, the original plan was to upgrade to Glyphs version 3, convert/upgrade the fonts, upload the masters in the new git-friendly format to https://github.com/cormullion/juliamonomaster (Glyphs version 2.0 format used monolithic files that aren't git-friendly), and set the version to 1.0. 

However, this plan is struggling, because the 2 -> 3 upgrade didn't go well; I used the time-limited demo period to test the conversion, and I simply ran out of time dealing with all the problems the changes in Glyphs3 caused (browse the glyphs forum for details). When I get some more time, possibly over Christmas, I will buy Glyphs3 and re-try the upgrade and hopefully the most recent version will cause fewer problems. Not sure when this will happen, but if you watch that repo you'll be the second to know... 😀

**Comment by cormullion** [comment]
hopefully fixed for v0.044

**Comment by cata0309** [comment]
Where can I found the source files?

**Comment by cmarincia** [comment]
@cormullion any updates on this?

**Comment by cormullion** [comment]
https://github.com/cormullion/juliamono/issues/90#issuecomment-981056386

**Comment by cmarincia** [comment]
Thank you! I didn't look at the repo link. Sorry for pinging you!
